apiVersion: v1
kind: Service
metadata:
  name: {{ include "flame-archive-exporter.fullname" . }}
  labels:
    {{- include "flame-archive-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "flame-archive-exporter.selectorLabels" . | nindent 4 }}
